class ePin:
    IN: int
    OUT: int
    PWM: int
    IRQ_RISING: int
    IRQ_FALLING: int

    def __init__(self, *_args, **_kwargs) -> None: ...
    def init(self, *_args, **_kwargs) -> None: ...
    def value(self, *_args) -> int: ...
    def duty(self, *_args) -> int: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def irq(self, *_args, **_kwargs) -> None: ...
    def deinit(self) -> None: ...
